# Generated by Django 2.2.4 on 2019-09-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190826_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='background',
            field=models.TextField(default=12),
            preserve_default=False,
        ),
    ]
